# Generated from rspec-core-2.8.0.gem by gem2rpm5 0.6.7 -*- rpm-spec -*-
%define	rbname	rspec-core

Summary:	Rspec-core-2.8.0
Name:		rubygem-%{rbname}

Version:	3.1.4
Release:	1
Group:		Development/Ruby
License:	GPLv2+ or Ruby
URL:		http://github.com/rspec/rspec-core
Source0:	http://rubygems.org/gems/rspec-core-3.1.4.gem
BuildRequires:	rubygems 
BuildArch:	noarch

%description
BDD for Ruby. RSpec runner and example groups.

%package	doc
Summary:	Documentation for %{name}
Group:		Books/Computer books
Requires:	%{name} = %{EVRD}

%description	doc
Documents, RDoc & RI documentation for %{name}.

%prep
%setup -q

%build
%gem_build -f '(features|spec)'

%install
%gem_install

%files
# %{_bindir}/autospec
# %{_bindir}/rspec
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}
# %dir %{ruby_gemdir}/gems/%{rbname}-%{version}/exe
# %{ruby_gemdir}/gems/%{rbname}-%{version}/exe/autospec
# %{ruby_gemdir}/gems/%{rbname}-%{version}/exe/rspec
%dir %{ruby_gemdir}/gems/%{rbname}-%{version}/lib/
# %{ruby_gemdir}/gems/%{rbname}-%{version}/lib/*
%{ruby_gemdir}/specifications/%{rbname}-%{version}.gemspec
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/Object.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RR.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RR/Errors.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/AnonymousExampleGroup.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Backports.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Backports/Random.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Backports/Random/Implementation.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Backports/Random/MT19937.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Backports/RandomNumberGenerator.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/BacktraceFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Configuration.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Configuration/DeprecationReporterBuffer.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Configuration/ExposeCurrentExample.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Configuration/MustBeConfiguredBeforeExampleGroupsError.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Configuration/host;.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/ConfigurationOptions.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/DRbOptions.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/DRbRunner.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/DSL.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/DSL/RSpec.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/DSL/top_level;.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Example.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Example/ExecutionResult.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Example/Procsy.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/ExampleGroup.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/ExclusionRules.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/FilterManager.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/FilterRules.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/FlatMap.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/BaseFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/BaseTextFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/ConsoleCodes.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DeprecationFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DeprecationFormatter/DelayedPrinter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DeprecationFormatter/FileStream.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DeprecationFormatter/ImmediatePrinter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DeprecationFormatter/RaiseErrorStream.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/DocumentationFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/Helpers.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/HtmlFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/HtmlPrinter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/JsonFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/Loader.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/ProfileFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/ProgressFormatter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/Protocol.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/SnippetExtractor.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/SnippetExtractor/CoderayConverter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Formatters/SnippetExtractor/NullConverter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/HashImitatable.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/HashImitatable/ClassMethods.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/AfterContextHook.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/AfterHook.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/AroundHook.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/AroundHookCollection.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/BaseHookCollection.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/BeforeHook.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/GroupHookCollection.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/Hook.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/HookCollection.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Hooks/HookCollections.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/InclusionRules.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/LegacyExampleGroupHash.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MemoizedHelpers.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MemoizedHelpers/ClassMethods.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/After.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/Before.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Metadata.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Metadata/ExampleGroupHash.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Metadata/ExampleHash.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Metadata/HashPopulator.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MetadataFilter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MinitestAssertionsAdapter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters/Flexmock.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters/Mocha.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters/Null.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters/RR.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/MockingAdapters/RSpec.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications/ExamplesNotification.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications/FailedExampleNotification.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications/NullColorizer.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications/NullNotification.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Notifications/PendingExampleFixedNotification.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering/ConfigurationManager.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering/Custom.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering/Identity.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering/Random.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Ordering/Registry.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Parser.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Pending.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Pending/PendingExampleFixedError.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Pending/SkipDeclaredInExample.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/ProjectInitializer.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/RakeTask.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/RakeTask/Rake.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Reporter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/RubyProject.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Runner.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SharedContext.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SharedExampleGroup.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SharedExampleGroup/Registry.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SharedExampleGroup/Registry/mod;.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SharedExampleGroup/TopLevelDSL.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/SuiteHookContext.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/TestUnitAssertionsAdapter.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/TestUnitAssertionsAdapter/Minitest.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Time.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Version.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/Warnings.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/Core/World.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/RSpec/ExampleGroups.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts.css
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/Lato-Light.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/Lato-LightItalic.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/Lato-Regular.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/Lato-RegularItalic.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/SourceCodePro-Bold.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/fonts/SourceCodePro-Regular.ttf
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/add.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/arrow_up.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/brick.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/brick_link.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/bug.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/bullet_black.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/bullet_toggle_minus.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/bullet_toggle_plus.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/date.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/delete.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/find.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/loadingAnimation.gif
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/macFFBgHack.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/package.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/page_green.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/page_white_text.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/page_white_width.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/plugin.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/ruby.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/tag_blue.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/tag_green.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/transparent.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/wrench.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/wrench_orange.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/images/zoom.png
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/index.html
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/darkfish.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/jquery.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/navigation.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/search.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/search_index.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/js/searcher.js
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/rdoc.css
%{_datadir}/gems/doc/rspec-core-3.1.4/rdoc/table_of_contents.html
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/Object/cdesc-Object.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RR/Errors/cdesc-Errors.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RR/cdesc-RR.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/AnonymousExampleGroup/cdesc-AnonymousExampleGroup.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/%3d%3d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/_rand_range-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/bytes-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/cdesc-Implementation.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/left-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/marshal_dump-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/marshal_load-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/rand-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/seed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/seed_rand-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/Implementation/state-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/%5b%5d-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/cdesc-MT19937.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/convert_seed-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/left-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/marshal_dump-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/marshal_load-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/mask_32_bits-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/next_state-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/random_32_bits-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/random_bytes-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/random_float-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/random_integer-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/seed%3d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/MT19937/state_as_bignum-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/cdesc-Random.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/Random/new_seed-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/RandomNumberGenerator/cdesc-RandomNumberGenerator.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/RandomNumberGenerator/new_seed-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/cdesc-Backports.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/coerce_to-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Backports/coerce_to_int-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/backtrace_line-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/cdesc-BacktraceFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/exclude%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/exclusion_patterns-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/filter_gem-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/format_backtrace-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/full_backtrace%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/full_backtrace-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/inclusion_patterns-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/matches%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/BacktraceFormatter/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Configuration/DeprecationReporterBuffer/cdesc-DeprecationReporterBuffer.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Configuration/ExposeCurrentExample/cdesc-ExposeCurrentExample.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Configuration/MustBeConfiguredBeforeExampleGroupsError/cdesc-MustBeConfiguredBeforeExampleGroupsError.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Configuration/cdesc-Configuration.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Configuration/host;/cdesc-host;.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/args_from_options_file-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/cdesc-ConfigurationOptions.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/command_line_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/configure-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/configure_filter_manager-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/custom_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/custom_options_file-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/env_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/file_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/force%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/global_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/global_options_file-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/load_formatters_into-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/local_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/local_options_file-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/options_file_as_erb_string-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/options_from-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/order-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/organize_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/process_options_into-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/project_options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ConfigurationOptions/project_options_file-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_failure_exit_code-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_formatters-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_full_description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_libs-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/add_requires-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/cdesc-DRbOptions.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbOptions/options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbRunner/cdesc-DRbRunner.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbRunner/drb_argv-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbRunner/drb_port-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbRunner/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DRbRunner/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/RSpec/cdesc-RSpec.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/cdesc-DSL.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/change_global_dsl-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/example_group_aliases-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/expose_example_group_alias-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/expose_example_group_alias_globally-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/expose_globally%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/exposed_globally%3f-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/remove_globally%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/top_level-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/DSL/top_level;/cdesc-top_level;.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/cdesc-ExecutionResult.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/finished_at-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/get_value-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/hash_for_delegation-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/issue_deprecation-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/pending_exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/pending_fixed%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/pending_fixed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/pending_message-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/record_finished-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/run_time-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/set_value-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/started_at-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/ExecutionResult/status-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/call-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/cdesc-Procsy.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/example-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/executed%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/inspect-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/to_proc-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/Procsy/wrap-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/all_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/any_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/around_example_hooks-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/assign_generated_description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/cdesc-Example.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/clock-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/delegate_to_metadata-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/example_group-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/example_group_instance-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/fail_with_exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/finish-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/instance_exec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/instance_exec_with_rescue-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/metadata-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/mocks_need_verification%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/record_finished-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/run_after_example-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/run_before_example-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/set_exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/skip_message-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/skip_with_exception-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/start-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/verify_mocks-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Example/with_around_example_hooks-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ExampleGroup/cdesc-ExampleGroup.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ExclusionRules/cdesc-ExclusionRules.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ExclusionRules/include_example%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/add_location-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/cdesc-FilterManager.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/empty%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/exclude%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/exclude-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/exclude_only-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/exclude_with_low_priority-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/exclusions-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/include%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/include-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/include_only-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/include_with_low_priority-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/inclusions-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterManager/prune-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/%5b%5d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/add-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/add_with_low_priority-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/build-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/cdesc-FilterRules.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/clear-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/delete-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/each_pair-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/empty%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/fetch-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/opposite-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/rules-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FilterRules/use_only-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FlatMap/cdesc-FlatMap.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FlatMap/flat_map-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/FlatMap/flat_map-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/BaseFormatter/cdesc-BaseFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/BaseTextFormatter/cdesc-BaseTextFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ConsoleCodes/cdesc-ConsoleCodes.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ConsoleCodes/configuration_color-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ConsoleCodes/console_code_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ConsoleCodes/wrap-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DeprecationFormatter/DelayedPrinter/cdesc-DelayedPrinter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DeprecationFormatter/FileStream/cdesc-FileStream.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DeprecationFormatter/ImmediatePrinter/cdesc-ImmediatePrinter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DeprecationFormatter/RaiseErrorStream/cdesc-RaiseErrorStream.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DeprecationFormatter/cdesc-DeprecationFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/DocumentationFormatter/cdesc-DocumentationFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Helpers/cdesc-Helpers.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Helpers/format_duration-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Helpers/format_seconds-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Helpers/pluralize-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Helpers/strip_trailing_zeroes-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlFormatter/cdesc-HtmlFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/cdesc-HtmlPrinter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/flush-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/indentation_style-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/make_example_group_header_red-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/make_example_group_header_yellow-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/make_header_red-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/make_header_yellow-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/move_progress-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_example_failed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_example_group_end-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_example_group_start-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_example_passed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_example_pending-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_html_start-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/HtmlPrinter/print_summary-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/JsonFormatter/cdesc-JsonFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/add-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/built_in_formatter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/cdesc-Loader.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/custom_formatter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/default_formatter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/duplicate_formatter_exists%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/existing_formatter_implements%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/file_at-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/find_formatter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/formatters-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/formatters-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/notifications_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/path_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/reporter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/setup_default-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/string_const%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/underscore-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Loader/underscore_with_fix_for_non_standard_rspec_naming-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ProfileFormatter/cdesc-ProfileFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/ProgressFormatter/cdesc-ProgressFormatter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/Protocol/cdesc-Protocol.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/CoderayConverter/cdesc-CoderayConverter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/CoderayConverter/convert-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/NullConverter/cdesc-NullConverter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/NullConverter/convert-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/cdesc-SnippetExtractor.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/lines_around-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/post_process-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/snippet-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/SnippetExtractor/snippet_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/cdesc-Formatters.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Formatters/register-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/HashImitatable/ClassMethods/cdesc-ClassMethods.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/HashImitatable/cdesc-HashImitatable.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AfterContextHook/cdesc-AfterContextHook.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AfterContextHook/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AfterHook/cdesc-AfterHook.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AfterHook/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHook/cdesc-AroundHook.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHook/execute_with-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHook/hook_description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHookCollection/cdesc-AroundHookCollection.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHookCollection/for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHookCollection/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/AroundHookCollection/with-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/BaseHookCollection/cdesc-BaseHookCollection.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/BaseHookCollection/hooks-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/BaseHookCollection/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/BeforeHook/cdesc-BeforeHook.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/BeforeHook/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/GroupHookCollection/cdesc-GroupHookCollection.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/GroupHookCollection/for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/GroupHookCollection/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/Hook/block-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/Hook/cdesc-Hook.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/Hook/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/Hook/options-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/Hook/options_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollection/cdesc-HookCollection.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollection/for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollection/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollection/with-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/%5b%5d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/after_context_hooks_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/after_example_hooks_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/around_example_hooks_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/before_context_hooks_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/before_example_hooks_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/cdesc-HookCollections.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/extract_scope_from-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/find_hook-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/known_scope%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/normalized_scope_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/process-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/register-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/register_globals-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/HookCollections/scope_and_options_from-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/after-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/append_after-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/append_before-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/around-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/before-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/cdesc-Hooks.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/hooks-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/prepend_after-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Hooks/prepend_before-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/add-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/add_location-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/add_with_low_priority-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/apply_standalone_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/cdesc-InclusionRules.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/include_example%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/is_standalone_filter%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/replace_filters-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/standalone%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/InclusionRules/use-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/LegacyExampleGroupHash/cdesc-LegacyExampleGroupHash.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ClassMethods/cdesc-ClassMethods.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ClassMethods/let%21-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ClassMethods/let-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ClassMethods/subject%21-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ClassMethods/subject-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/After/article-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/After/cdesc-After.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/After/hook_expression-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/After/hook_intention-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/Before/article-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/Before/cdesc-Before.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/Before/hook_expression-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/Before/hook_intention-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/cdesc-ContextHookMemoizedHash.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/fetch-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/ContextHookMemoizedHash/isolate_for_context_hook-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/__memoized-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/cdesc-MemoizedHelpers.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/define_helpers_on-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/get_constant_or_yield-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/is_expected-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/module_for-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/should-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/should_not-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MemoizedHelpers/subject-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/backwards_compatibility_default_proc-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/cdesc-ExampleGroupHash.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/create-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/described_class-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/full_description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleGroupHash/hash_with_backwards_compatibility_default_proc-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleHash/cdesc-ExampleHash.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleHash/create-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleHash/described_class-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/ExampleHash/full_description-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/block-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/build_description_from-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/cdesc-HashPopulator.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/description_args-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/description_separator-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/ensure_valid_user_keys-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/file_path_and_line_number_from-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/metadata-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/populate-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/populate_location_attributes-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/HashPopulator/user_metadata-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/backtrace_from-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/build_hash_from-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/cdesc-Metadata.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Metadata/relative_path-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/all_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/any_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/cdesc-MetadataFilter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/example_group_declaration_line-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/filter_applies%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/filter_applies_to_any_value%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/filters_apply%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/line_number_filter_applies%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/location_filter_applies%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/parent_of-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/relevant_line_numbers-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MetadataFilter/silence_metadata_example_group_deprecations-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MinitestAssertionsAdapter/assertions-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MinitestAssertionsAdapter/cdesc-MinitestAssertionsAdapter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Flexmock/cdesc-Flexmock.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Flexmock/framework_name-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Flexmock/setup_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Flexmock/teardown_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Flexmock/verify_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Mocha/cdesc-Mocha.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Mocha/framework_name-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Mocha/setup_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Mocha/teardown_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Mocha/verify_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Null/cdesc-Null.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Null/setup_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Null/teardown_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/Null/verify_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RR/cdesc-RR.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RR/framework_name-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RR/setup_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RR/teardown_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RR/verify_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/cdesc-RSpec.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/configuration-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/framework_name-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/setup_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/teardown_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/RSpec/verify_mocks_for_rspec-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/MockingAdapters/cdesc-MockingAdapters.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/ExamplesNotification/cdesc-ExamplesNotification.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/FailedExampleNotification/cdesc-FailedExampleNotification.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/NullColorizer/cdesc-NullColorizer.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/NullNotification/cdesc-NullNotification.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/PendingExampleFixedNotification/cdesc-PendingExampleFixedNotification.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Notifications/cdesc-Notifications.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/cdesc-ConfigurationManager.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/force-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/order%3d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/ordering_registry-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/register_ordering-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/seed%3d-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/seed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/ConfigurationManager/seed_used%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Custom/cdesc-Custom.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Custom/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Custom/order-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Identity/cdesc-Identity.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Identity/order-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Random/cdesc-Random.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Random/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Random/order-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Random/shuffle-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Random/used%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Registry/cdesc-Registry.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Registry/fetch-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Registry/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Registry/register-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/Registry/used_random_seed%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Ordering/cdesc-Ordering.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Parser/cdesc-Parser.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Parser/parse-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Parser/parse-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Parser/parser-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/PendingExampleFixedError/cdesc-PendingExampleFixedError.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/SkipDeclaredInExample/argument-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/SkipDeclaredInExample/cdesc-SkipDeclaredInExample.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/SkipDeclaredInExample/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/cdesc-Pending.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/mark_fixed%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/mark_pending%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/mark_skipped%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/pending-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Pending/skip-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/ProjectInitializer/cdesc-ProjectInitializer.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/Rake/cdesc-Rake.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/blank-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/cdesc-RakeTask.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/define-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/exclude_pattern-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/fail_on_error-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/failure_message-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/file_exclusion_specification-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/file_inclusion_specification-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/name-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/pattern-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/rspec_load_path-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/rspec_opts-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/rspec_path-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/ruby_opts-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/run_task-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/spec_command-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RakeTask/verbose-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/cdesc-Reporter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/deprecation-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_failed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_group_finished-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_group_started-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_passed-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_pending-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/example_started-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/failed_examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/finish-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/message-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/mute_profile_output%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/notify-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/pending_examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/register_listener-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/registered_listeners-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/report-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/seed_used%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/start-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Reporter/stop-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/add_dir_to_load_path-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/add_dir_to_load_path-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/add_to_load_path-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/add_to_load_path-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/ascend_until-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/ascend_until-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/cdesc-RubyProject.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/determine_root-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/determine_root-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/find_first_parent_containing-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/find_first_parent_containing-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/root-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/RubyProject/root-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/autorun-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/autorun_disabled%3f-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/cdesc-Runner.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/disable_autorun%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/installed_at_exit%3f-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/invoke-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/run-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/run-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/run_specs-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/running_in_drb%3f-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/setup-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Runner/trap_interrupt-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedContext/__shared_context_recordings-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedContext/cdesc-SharedContext.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedContext/included-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedContext/record-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/add-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/cdesc-Registry.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/ensure_block_has_source_location-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/find-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/formatted_location-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/mod;/cdesc-mod;.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/shared_example_groups-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/valid_name%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/Registry/warn_if_key_taken-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/cdesc-TopLevelDSL.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/definitions-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/expose_globally%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/exposed_globally%3f-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/remove_globally%21-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/TopLevelDSL/shared_examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/cdesc-SharedExampleGroup.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/shared_context-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/shared_examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SharedExampleGroup/shared_examples_for-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/SuiteHookContext/cdesc-SuiteHookContext.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/TestUnitAssertionsAdapter/Minitest/cdesc-Minitest.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/TestUnitAssertionsAdapter/cdesc-TestUnitAssertionsAdapter.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Time/cdesc-Time.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Version/cdesc-Version.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Warnings/cdesc-Warnings.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Warnings/deprecate-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Warnings/warn_deprecation-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/Warnings/warn_with-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/announce_exclusion_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/announce_filters-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/announce_inclusion_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/cdesc-World.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/clear_remaining_example_groups-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/configure_group-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/declaration_line_numbers-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/everything_filtered_message-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/example_count-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/example_groups-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/exclusion_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/filter_manager-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/filtered_examples-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/inclusion_filter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/new-c.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/ordered_example_groups-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/preceding_declaration_line-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/register-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/reporter-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/reset-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/shared_example_group_registry-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/wants_to_quit-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/World/windows_os%3f-i.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/Core/cdesc-Core.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/ExampleGroups/cdesc-ExampleGroups.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/RSpec/cdesc-RSpec.ri
%{_datadir}/gems/doc/rspec-core-3.1.4/ri/cache.ri
# %{_datadir}/gems/gems/rspec-core-3.1.4/exe/rspec
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/autorun.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/backport_random.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/backtrace_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/configuration.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/configuration_options.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/drb.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/dsl.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/example.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/example_group.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/filter_manager.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/flat_map.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/base_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/base_text_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/console_codes.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/deprecation_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/documentation_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/helpers.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/html_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/html_printer.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/json_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/profile_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/progress_formatter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/protocol.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/formatters/snippet_extractor.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/hooks.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/memoized_helpers.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/metadata.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/metadata_filter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/minitest_assertions_adapter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/mocking_adapters/flexmock.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/mocking_adapters/mocha.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/mocking_adapters/null.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/mocking_adapters/rr.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/mocking_adapters/rspec.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/notifications.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/option_parser.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/ordering.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/pending.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/project_initializer.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/project_initializer/.rspec
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/project_initializer/spec/spec_helper.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/rake_task.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/reporter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/ruby_project.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/runner.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/shared_context.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/shared_example_group.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/test_unit_assertions_adapter.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/version.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/warnings.rb
%{_datadir}/gems/gems/rspec-core-3.1.4/lib/rspec/core/world.rb
# %{_datadir}/gems/specifications/rspec-core-3.1.4.gemspec

%files doc
%{ruby_gemdir}/doc/%{rbname}-%{version}
%{ruby_gemdir}/gems/%{rbname}-%{version}/*.md
%{ruby_gemdir}/gems/%{rbname}-%{version}/*.txt
# %dir %{ruby_gemdir}/gems/%{rbname}-%{version}/features
# %{ruby_gemdir}/gems/%{rbname}-%{version}/features/*
# %dir %{ruby_gemdir}/gems/%{rbname}-%{version}/spec
# %{ruby_gemdir}/gems/%{rbname}-%{version}/spec/*
